packages:
  - apps/web/marketing
  - apps/web/app

allowBuilds:
  vue-demi: true
  esbuild: true
  sharp: true
  maplibre-gl: true

minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.5'
  - vue-tsc@3.3.5
  - '@vue/devtools-core@8.1.3'
  - '@vue/devtools-kit@8.1.3'
  - '@vue/devtools-shared@8.1.3'
  - vite-plugin-vue-devtools@8.1.3

overrides:
  esbuild: ">=0.28.1"
