packages:
  - apps/web/marketing
  - apps/web/app
  - apps/web/admin
  - tools/compliance
  - shared/web

minimumReleaseAge: 4320

allowBuilds:
  vue-demi: true
  esbuild: true
  sharp: true
  maplibre-gl: true

minimumReleaseAgeExclude:
  - '@lucide/vue@1.34.0'
  - 'vue-i18n@11.4.9'
  - '@intlify/core-base@11.4.9'
  - '@intlify/devtools-types@11.4.9'
  - '@intlify/message-compiler@11.4.9'
  - '@intlify/shared@11.4.9'
