import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { test } from 'node:test'

const generator = path.resolve('.agents/scripts/regen-skill-registry.mjs')

const runGenerator = (args) => new Promise((resolve, reject) => {
  const child = spawn(process.execPath, [generator, ...args], { stdio: ['ignore', 'pipe', 'pipe'] })
  let stdout = ''
  let stderr = ''
  child.stdout.on('data', (chunk) => { stdout += chunk })
  child.stderr.on('data', (chunk) => { stderr += chunk })
  child.on('error', reject)
  child.on('close', (code) => resolve({ code, stdout, stderr }))
})

const skill = (name, description, metadata) => [
  '---',
  `name: ${name}`,
  'description: >',
  `  ${description}`,
  'metadata:',
  ...Object.entries(metadata).map(([key, value]) => `  ${key}: ${value}`),
  '---',
  `# ${name}`,
].join('\n')

test('generates sorted registry entries from direct skill folders only', async () => {
  const root = await mkdtemp(path.join(tmpdir(), 'skill-registry-'))
  const skills = path.join(root, 'skills')
  const output = path.join(root, 'registry.md')
  await writeFile(path.join(root, 'placeholder'), '')
  await import('node:fs/promises').then(({ mkdir }) => Promise.all([
    mkdir(path.join(skills, 'zeta'), { recursive: true }),
    mkdir(path.join(skills, 'alpha'), { recursive: true }),
    mkdir(path.join(skills, 'nested', 'child'), { recursive: true }),
  ]))
  await writeFile(path.join(skills, 'zeta', 'SKILL.md'), skill('zeta', 'Zeta skill', {
    category: 'governance',
    family: 'none',
    source: 'local',
    version: '2026-09-28',
  }))
  await writeFile(path.join(skills, 'alpha', 'SKILL.md'), skill('alpha', 'Alpha skill', {
    category: 'testing',
    family: 'vitest',
    source: 'upstream-adapted',
    version: '2026-09-27',
  }))
  await writeFile(path.join(skills, 'nested', 'child', 'SKILL.md'), skill('child', 'Nested skill', {
    category: 'testing',
    family: 'none',
    source: 'local',
    version: '2026-09-27',
  }))

  const generated = await runGenerator(['--skills-dir', skills, '--output', output])
  assert.equal(generated.code, 0)
  const registry = await readFile(output, 'utf8')
  assert.match(registry, /<!-- AUTO-GENERATED by \.agents\/scripts\/regen-skill-registry\.mjs -->/)
  assert.match(registry, /> Source: \.agents\/skills\/\*\/SKILL\.md \(2 top-level skills\)\./)
  assert.ok(registry.indexOf('| `alpha` |') < registry.indexOf('| `zeta` |'))
  assert.match(registry, /\| `alpha` \| testing \| vitest \| upstream-adapted \| 2026-09-27 \| Alpha skill \|/)
  assert.doesNotMatch(registry, /Nested skill|`nested`/)

  const clean = await runGenerator(['--skills-dir', skills, '--output', output, '--check'])
  assert.equal(clean.code, 0)
  await writeFile(output, `${registry}drift\n`)
  const drift = await runGenerator(['--skills-dir', skills, '--output', output, '--check'])
  assert.equal(drift.code, 1)
  assert.match(drift.stderr, /Registry drift detected/)
  await rm(root, { recursive: true, force: true })
})
