import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { test } from 'node:test'

const scanner = path.resolve('.agents/scripts/skill-comment-scan.mjs')

const runScanner = (root, allowlist, all = true) => new Promise((resolve, reject) => {
  const childArguments = [scanner, '--paths', root, '--allowlist', allowlist, ...(all ? ['--all'] : []), '--json']
  const child = spawn(process.execPath, childArguments, {
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  let stdout = ''
  let stderr = ''
  child.stdout.on('data', (chunk) => { stdout += chunk })
  child.stderr.on('data', (chunk) => { stderr += chunk })
  child.on('error', reject)
  child.on('close', (code) => resolve({ code, stdout, stderr }))
})

test('detects each prohibited comment group and explicit policy token', async () => {
  const root = await mkdtemp(path.join(tmpdir(), 'skill-comment-scan-'))
  const allowlist = path.join(root, 'allowlist.json')
  await writeFile(allowlist, '[]')
  await writeFile(path.join(root, 'kotlin.kt'), '// forbidden\n')
  await writeFile(path.join(root, 'kdoc.kt'), '/**\n * forbidden\n */\n')
  await writeFile(path.join(root, 'script.ts'), '// forbidden\n')
  await writeFile(path.join(root, 'guide.md'), '<!-- forbidden -->\n')
  await writeFile(path.join(root, 'script.sh'), '# forbidden\n')
  await writeFile(path.join(root, 'todo.ts'), 'const value = "TODO"\n')
  await writeFile(path.join(root, 'suppression.ts'), 'biome-ignore\n')

  const result = await runScanner(root, allowlist)
  const report = JSON.parse(result.stdout)

  assert.equal(result.code, 1)
  assert.equal(report.violations.length, 7)
  assert.deepEqual(new Set(report.violations.map(({ patternId }) => patternId)), new Set([
    'line-comment',
    'kdoc-continuation',
    'html-comment',
    'hash-comment',
    'policy-token',
  ]))

  await rm(root, { recursive: true, force: true })
})

test('allows shebangs, SPDX headers, generated markers, and allowlisted paths', async () => {
  const root = await mkdtemp(path.join(tmpdir(), 'skill-comment-scan-'))
  const allowlist = path.join(root, 'allowlist.json')
  const allowed = path.join(root, 'allowed.ts')
  await writeFile(allowlist, JSON.stringify([{ path: 'allowed.ts', reason: 'fixture exception' }]))
  await writeFile(path.join(root, 'script.sh'), '#!/usr/bin/env bash\nvalue=true\n')
  await writeFile(path.join(root, 'license.kt'), '// SPDX-License-Identifier: Apache-2.0\nval value = true\n')
  await writeFile(path.join(root, 'generated.ts'), '// AUTO-GENERATED by fixture\nconst value = true\n')
  await writeFile(allowed, '// intentionally allowlisted\n')

  const result = await runScanner(root, allowlist)
  const report = JSON.parse(result.stdout)

  assert.equal(result.code, 0)
  assert.deepEqual(report.violations, [])

  await rm(root, { recursive: true, force: true })
})
