load("@rules_kotlin//kotlin:core.bzl", "kt_kotlinc_options")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

kt_kotlinc_options(
    name = "common_kotlinc_opts",
    jvm_target = "21",
    x_annotation_default_target = "param-property",
    x_jsr_305 = "strict",
)

kt_jvm_library(
    name = "common_lib",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    deps = [
        "@maven//:org_jetbrains_kotlin_kotlin_reflect",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm",
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:tools_jackson_module_jackson_module_kotlin",
    ],
    kotlinc_opts = ":common_kotlinc_opts",
)
