package com.profiletailors.smp.media.infrastructure.persistence

import com.profiletailors.smp.integration.support.DatabaseUnitTestBase
import com.profiletailors.smp.media.domain.MediaAssetStatus
import kotlinx.coroutines.reactor.awaitSingle
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.time.Instant

/**
 * H2-backed unit tests for [R2dbcMediaAssetRepository]. Lives outside the `postgres` tag so the
 * CI coverage gate picks it up. Uses [DatabaseUnitTestBase] which spins up H2 in PostgreSQL
 * compatibility mode and runs Liquibase migrations — sufficient to exercise the SQL generated by
 * `findActiveByWorkspaceAndHash` (which uses standard `WHERE` / `ORDER BY` constructs, not the
 * Postgres-only partial unique index).
 */
class R2dbcMediaAssetRepositoryTest : DatabaseUnitTestBase() {

    private lateinit var mediaRepository: R2dbcMediaAssetRepository
    private var workspaceCounter = 0

    override fun databaseName(): String = "media_asset_repository_unit"

    /**
     * Override the base cleanup to also wipe `workspace_file_blobs` and the additional tables
     * this test seeds — the parent's default cleanup leaves `workspace_file_blobs` populated,
     * which causes PK violations when [seedBlob] runs in the next test's `setUp()`.
     */
    override suspend fun cleanupTables() {
        // Replicate the parent's full cleanup (it isn't called when we override `cleanupTables`)
        // and add the table this test actually needs to wipe.
        databaseClient.sql("DELETE FROM delivery_attempts").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM publication_jobs").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM publication_asset_links").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM publications").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM media_assets").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM publication_assets").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM social_accounts").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM social_connections").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM secure_credentials").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM audit_events").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM workspace_target_scopes").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM workspace_direct_grants").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM workspace_entitlements").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM membership_roles").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM role_permissions").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM roles").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM permissions").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM workspace_memberships").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM workspace_ownerships").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM workspace_file_blobs").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM workspaces").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM refresh_sessions").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM api_key_credentials").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM service_account_credentials").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM local_password_credentials").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM email_verification_tokens").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM user_identities").fetch().rowsUpdated().awaitSingle()
        databaseClient.sql("DELETE FROM principals").fetch().rowsUpdated().awaitSingle()
    }

    private fun nextWorkspaceId(): String {
        workspaceCounter += 1
        return "ws-test-$workspaceCounter"
    }

    @BeforeEach
    fun setUp() = runTest {
        mediaRepository = R2dbcMediaAssetRepository(databaseClient)
    }

    private suspend fun seedWorkspace(workspaceId: String) {
        databaseClient.sql(
            """
            INSERT INTO workspaces (id, name, status, icon)
            VALUES (:workspaceId, 'Workspace', 'ACTIVE', NULL)
            """.trimIndent(),
        )
            .bind("workspaceId", workspaceId)
            .fetch()
            .rowsUpdated()
            .awaitSingle()
    }

    private suspend fun seedBlob(workspaceId: String, fileHash: String) {
        databaseClient.sql(
            """
            INSERT INTO workspace_file_blobs (workspace_id, file_hash, status)
            VALUES (:workspaceId, :fileHash, 'READY')
            """.trimIndent(),
        )
            .bind("workspaceId", workspaceId)
            .bind("fileHash", fileHash)
            .fetch()
            .rowsUpdated()
            .awaitSingle()
    }

    @Test
    fun `findActiveByWorkspaceAndHash returns the active asset that references the hash`() = runTest {
        val workspaceId = nextWorkspaceId()
        seedWorkspace(workspaceId)
        seedBlob(workspaceId, HASH_A)
        insertAsset(workspaceId = workspaceId, assetId = "asset-a", fileHash = HASH_A, status = "READY")
        insertAsset(workspaceId = workspaceId, assetId = "asset-b", fileHash = HASH_A, status = "READY")

        val active = mediaRepository.findActiveByWorkspaceAndHash(workspaceId, HASH_A)

        assertNotNull(active)
        assertEquals("asset-a", active!!.assetId, "oldest active asset by created_at wins")
        assertEquals(MediaAssetStatus.READY, active.status)
    }

    @Test
    fun `findActiveByWorkspaceAndHash ignores DELETED and FAILED rows`() = runTest {
        val workspaceId = nextWorkspaceId()
        seedWorkspace(workspaceId)
        seedBlob(workspaceId, HASH_A)
        // Only DELETED + FAILED rows reference HASH_A — the lookup must return null so a
        // re-upload can proceed without colliding with soft-deleted history.
        insertAsset(workspaceId = workspaceId, assetId = "asset-deleted", fileHash = HASH_A, status = "DELETED")
        insertAsset(workspaceId = workspaceId, assetId = "asset-failed", fileHash = HASH_A, status = "FAILED")

        val active = mediaRepository.findActiveByWorkspaceAndHash(workspaceId, HASH_A)

        assertNull(active, "DELETED/FAILED must not block re-upload of the same hash")
    }

    private suspend fun insertAsset(workspaceId: String, assetId: String, fileHash: String, status: String) {
        databaseClient.sql(
            """
            INSERT INTO media_assets (
                asset_id, workspace_id, source_type, file_hash, media_type, storage_key,
                original_filename, file_size_bytes, status, created_at
            ) VALUES (
                :assetId, :workspaceId, 'UPLOADED', :fileHash, 'image/png',
                CASE WHEN :status = 'READY' THEN 'assets/key.png' ELSE NULL END,
                'photo.png', 1024, :status, :createdAt
            )
            """.trimIndent(),
        )
            .bind("assetId", assetId)
            .bind("workspaceId", workspaceId)
            .bind("fileHash", fileHash)
            .bind("status", status)
            .bind("createdAt", Instant.now().atOffset(java.time.ZoneOffset.UTC))
            .fetch()
            .rowsUpdated()
            .awaitSingle()
    }

    companion object {
        private const val HASH_A = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    }
}
