# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
name: Cleanup caches for closed branches

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: dallay/common-actions/.github/workflows/cleanup-cache.yml@87129475c06d9f3354d398426926ba4345a4644d # v2.2.3
