# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
name: Cleanup caches for closed branches

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: dallay/common-actions/.github/workflows/cleanup-cache.yml@6548f0dfaad9e40648cd56e85566e5bc2d707dfb # v2.2.2
