# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
name: Cleanup caches for closed branches

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: dallay/common-actions/.github/workflows/cleanup-cache.yml@8aaf32edb1b70941a3f8889b47af1a7fd47e3a2c # v2.2.1
