name: Auto-merge dependencies
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-merge:
    uses: dallay/common-actions/.github/workflows/dependabot-auto-merge.yml@8aaf32edb1b70941a3f8889b47af1a7fd47e3a2c # v2.2.1
    with:
      target: squash
      approve: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}