name: Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: dallay/common-actions/.github/workflows/pr-labeler.yml@87129475c06d9f3354d398426926ba4345a4644d # v2.2.3
    with:
      configuration-path: .github/labeler.yaml
