name: Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: dallay/common-actions/.github/workflows/pr-labeler.yml@69060250307677655136ca88c70a2f77cb4153b2 # v2.2.4
    with:
      configuration-path: .github/labeler.yaml
