name: Semantic PR
permissions:
  contents: read
  pull-requests: write
on:
  pull_request_target:
    types: [opened, edited, synchronize]
jobs:
  main:
    uses: dallay/common-actions/.github/workflows/semantic-pr.yml@8aaf32edb1b70941a3f8889b47af1a7fd47e3a2c # v2.2.1