name: Semantic PR
permissions:
  contents: read
on:
  pull_request_target:
    types: [opened, edited, synchronize]
jobs:
  main:
    uses: dallay/common-actions/.github/workflows/semantic-pr.yml@6ecd716dcfb6a9e8a9c494d1eac210cc1d73d75f # v2.0.0