name: Semantic PR
permissions:
  contents: read
  pull-requests: write  # Required by the reusable semantic-pr.yml to post sticky PR status comments
on:
  pull_request_target:
    types: [opened, edited, synchronize]
jobs:
  main:
    uses: dallay/common-actions/.github/workflows/semantic-pr.yml@6548f0dfaad9e40648cd56e85566e5bc2d707dfb # v2.2.2