name: Sync labels 🏷️

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

concurrency:
  group: labels-sync-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  sync:
    uses: dallay/common-actions/.github/workflows/labels-sync.yml@87129475c06d9f3354d398426926ba4345a4644d # v2.2.3
