name: Sync labels 🏷️

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

concurrency:
  group: labels-sync-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  sync:
    uses: dallay/common-actions/.github/workflows/labels-sync.yml@6548f0dfaad9e40648cd56e85566e5bc2d707dfb # v2.2.2
