name: Sync labels 🏷️

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

concurrency:
  group: labels-sync-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  sync:
    uses: dallay/common-actions/.github/workflows/labels-sync.yml@69060250307677655136ca88c70a2f77cb4153b2 # v2.2.4
